FROM node:14 as build-step

RUN mkdir /app

WORKDIR /app

COPY package.json /app

RUN npm install

COPY . .

RUN npm run build users-management --skip-nx-cache

FROM nginx:1.17.1-alpine

COPY ./nginx-users-management.conf /etc/nginx/conf.d/default.conf

RUN mkdir /usr/share/nginx/html/users-management

COPY --from=build-step /app/dist/apps/users-management/* /usr/share/nginx/html/users-management/